"""SBOM (Software Bill of Materials) generator for ML models.

Generates a CycloneDX-compatible SBOM describing:
- Model identity and provenance
- Architecture and parameter count
- Training data provenance (when available)
- Framework dependencies
- Quantization method and parameters
- File hashes for integrity verification
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class SBOMGenerator:
    """Generate SBOM for ML models."""

    CYCLONEDX_VERSION = "1.5"
    SBOM_FORMAT = "CycloneDX"

    def generate(self, model_path: Path) -> str:
        """Generate a CycloneDX SBOM for a model.

        Args:
            model_path: Path to model file or directory.

        Returns:
            JSON string in CycloneDX format.
        """
        components = self._collect_components(model_path)

        bom = {
            "bomFormat": self.SBOM_FORMAT,
            "specVersion": self.CYCLONEDX_VERSION,
            "serialNumber": f"urn:uuid:{self._generate_uuid()}",
            "version": 1,
            "metadata": {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "tools": [
                    {
                        "vendor": "ModelGuard",
                        "name": "modelguard-sbom",
                        "version": "0.1.0",
                    }
                ],
                "component": {
                    "type": "machine-learning-model",
                    "name": model_path.name,
                    "description": "ML model SBOM generated by ModelGuard",
                    "hashes": self._compute_hashes(model_path),
                },
            },
            "components": components,
        }

        return json.dumps(bom, indent=2)

    def _collect_components(self, model_path: Path) -> list[dict[str, Any]]:
        """Collect all components from a model directory."""
        components: list[dict[str, Any]] = []

        if model_path.is_dir():
            # Model config
            config_path = model_path / "config.json"
            if config_path.exists():
                try:
                    with open(config_path) as f:
                        config = json.load(f)
                    components.append(self._config_to_component(config, config_path))
                except Exception:
                    pass

            # Tokenizer
            tokenizer_path = model_path / "tokenizer.json"
            if tokenizer_path.exists():
                components.append(
                    self._file_to_component(
                        tokenizer_path, "tokenizer", "tokenizer configuration"
                    )
                )

            # Weight files
            for ext in ["*.safetensors", "*.bin", "*.gguf", "*.pt"]:
                for weight_file in sorted(model_path.rglob(ext)):
                    components.append(
                        self._file_to_component(
                            weight_file, "model-weights", "model weight tensor file"
                        )
                    )

            # Model card
            readme = model_path / "README.md"
            if readme.exists():
                components.append(
                    self._file_to_component(
                        readme, "documentation", "model card"
                    )
                )

        elif model_path.is_file():
            components.append(
                self._file_to_component(
                    model_path, "model-weights", "model weight file"
                )
            )

        return components

    def _config_to_component(
        self, config: dict[str, Any], path: Path
    ) -> dict[str, Any]:
        """Convert a model config.json to a CycloneDX component."""
        arch = config.get("architectures", ["unknown"])[0]
        return {
            "type": "machine-learning-model",
            "name": arch,
            "description": f"Model architecture: {arch}",
            "hashes": self._compute_hashes(path),
            "properties": [
                {"name": "model_type", "value": config.get("model_type", "unknown")},
                {"name": "hidden_size", "value": str(config.get("hidden_size", "N/A"))},
                {
                    "name": "num_layers",
                    "value": str(
                        config.get("num_hidden_layers")
                        or config.get("num_layers", "N/A")
                    ),
                },
                {"name": "vocab_size", "value": str(config.get("vocab_size", "N/A"))},
            ],
        }

    def _file_to_component(
        self, path: Path, component_type: str, description: str
    ) -> dict[str, Any]:
        """Create a CycloneDX component from a file."""
        return {
            "type": component_type,
            "name": path.name,
            "description": description,
            "hashes": self._compute_hashes(path),
            "properties": [
                {"name": "file_size_bytes", "value": str(path.stat().st_size)},
            ],
        }

    @staticmethod
    def _compute_hashes(path: Path) -> list[dict[str, str]]:
        """Compute SHA-256 and SHA-1 hashes for a file."""
        sha256 = hashlib.sha256()
        sha1 = hashlib.sha1()

        if path.is_file():
            with open(path, "rb") as f:
                for chunk in iter(lambda: f.read(8192), b""):
                    sha256.update(chunk)
                    sha1.update(chunk)

        return [
            {"alg": "SHA-256", "content": sha256.hexdigest()},
            {"alg": "SHA-1", "content": sha1.hexdigest()},
        ]

    @staticmethod
    def _generate_uuid() -> str:
        """Generate a deterministic UUID from timestamp."""
        import uuid
        return str(uuid.uuid4())
